-- CX-705: Add marketing_cost_cents to cohorts for break-even calculation.
-- Defaults to 0; populated by future marketing sync module.
-- NOTE: Migration generated by drizzle-kit but trimmed to only the new column
-- (the cumulative content was due to a snapshot chain repair after parallel-branch merges).

ALTER TABLE "cohorts" ADD COLUMN "marketing_cost_cents" integer DEFAULT 0 NOT NULL;
