// Catalogul complet al rutelor CRM, așa cum sunt montate în server/app.ts.
// Matricile generice (neautentificat, id inexistent, id care nu e uuid, corp stricat, izolare
// între clienți) se generează din lista asta — deci o rută nouă adăugată aici primește automat
// zeci de scenarii. `scripts/e2e-crm/groups/catalog-sync.mjs` verifică că lista nu a rămas în
// urma codului (o rută din server/routes/crm*.ts care lipsește de aici face suita roșie).
//
// Câmpuri: [METODĂ, cale]. `:id`/`:leadId`/`:userId` = parametru. Flag-uri opționale:
//   public — ruta nu cere sesiune (formular public, cron cu secret): exclusă din matricea „anon".
//   file   — răspunsul nu e JSON (CSV).

export const ENDPOINTS = [
  // echipă
  ["GET", "/api/crm/team"],
  ["POST", "/api/crm/team/invites"],
  ["DELETE", "/api/crm/team/invites/:id"],
  ["PATCH", "/api/crm/team/members/:id"],
  ["PUT", "/api/crm/team/members/:id/access"],
  ["PUT", "/api/crm/team/members/:id/active"],
  // sănătate, etape, pâlnii, vederi salvate
  // Diagnostic de schemă, public prin design (server/routes/crmHealth.ts).
  ["GET", "/api/crm/health", { public: true }],
  ["GET", "/api/crm/stages"],
  ["POST", "/api/crm/stages"],
  ["POST", "/api/crm/stages/reorder"],
  ["PATCH", "/api/crm/stages/:id"],
  ["DELETE", "/api/crm/stages/:id"],
  ["GET", "/api/crm/pipelines"],
  ["POST", "/api/crm/pipelines"],
  ["PATCH", "/api/crm/pipelines/:id"],
  ["DELETE", "/api/crm/pipelines/:id"],
  ["GET", "/api/crm/saved-views"],
  ["POST", "/api/crm/saved-views"],
  ["PATCH", "/api/crm/saved-views/:id"],
  ["DELETE", "/api/crm/saved-views/:id"],
  // contacte, câmpuri personalizate, fișiere
  ["GET", "/api/crm/contacts"],
  ["POST", "/api/crm/contacts"],
  ["PATCH", "/api/crm/contacts/:id"],
  ["DELETE", "/api/crm/contacts/:id"],
  ["GET", "/api/crm/custom-fields/values"],
  ["PUT", "/api/crm/custom-fields/values"],
  ["GET", "/api/crm/custom-fields"],
  ["POST", "/api/crm/custom-fields"],
  ["PATCH", "/api/crm/custom-fields/:id"],
  ["DELETE", "/api/crm/custom-fields/:id"],
  ["GET", "/api/crm/lead-files"],
  ["POST", "/api/crm/lead-files/sign"],
  ["POST", "/api/crm/lead-files/finalize"],
  ["GET", "/api/crm/lead-files/:id/preview"],
  ["DELETE", "/api/crm/lead-files/:id"],
  // cadențe și reactivare
  ["GET", "/api/crm/cadences/reengagement/rules"],
  ["POST", "/api/crm/cadences/reengagement/rules"],
  ["PATCH", "/api/crm/cadences/reengagement/rules/:id"],
  ["DELETE", "/api/crm/cadences/reengagement/rules/:id"],
  ["GET", "/api/crm/cadences/reengagement/preview"],
  ["POST", "/api/crm/cadences/reengagement/run"],
  ["GET", "/api/crm/cadences/enrollments"],
  ["POST", "/api/crm/cadences/enroll"],
  ["POST", "/api/crm/cadences/enrollments/:id/cancel"],
  ["POST", "/api/crm/cadences/run"],
  ["GET", "/api/crm/cadences"],
  ["POST", "/api/crm/cadences"],
  ["PATCH", "/api/crm/cadences/:id"],
  ["DELETE", "/api/crm/cadences/:id"],
  // jurnal, drepturi, surse de captare, GDPR, formular public, cron
  ["GET", "/api/crm/audit"],
  ["GET", "/api/crm/permissions"],
  ["GET", "/api/crm/permissions/team"],
  ["PUT", "/api/crm/permissions/team"],
  ["GET", "/api/crm/capture-sources"],
  ["POST", "/api/crm/capture-sources"],
  ["PATCH", "/api/crm/capture-sources/:id"],
  ["DELETE", "/api/crm/capture-sources/:id"],
  ["GET", "/api/crm/gdpr/export/:leadId"],
  ["POST", "/api/crm/gdpr/anonymize/:leadId"],
  ["POST", "/api/crm/gdpr/revoke/:leadId"],
  ["POST", "/api/crm/intake/webform", { public: true }],
  ["GET", "/api/crm/cron/daily", { public: true }],
  ["POST", "/api/crm/cron/digest-now"],
  // rapoarte
  ["GET", "/api/crm/reports"],
  ["GET", "/api/crm/reports/funnel"],
  ["GET", "/api/crm/reports/layout"],
  ["PUT", "/api/crm/reports/layout"],
  // firme
  ["GET", "/api/crm/companies"],
  ["POST", "/api/crm/companies"],
  ["GET", "/api/crm/companies/duplicates"],
  ["POST", "/api/crm/companies/merge/preview"],
  ["POST", "/api/crm/companies/merge"],
  ["POST", "/api/crm/companies/import/preview"],
  ["POST", "/api/crm/companies/import/run"],
  ["PATCH", "/api/crm/companies/:id"],
  ["GET", "/api/crm/companies/:id/leads"],
  ["GET", "/api/crm/companies/:id/overview"],
  // etichete, motive de pierdere, taskuri
  ["GET", "/api/crm/tags/suggestions"],
  ["GET", "/api/crm/tags"],
  ["POST", "/api/crm/tags"],
  ["DELETE", "/api/crm/tags/:id"],
  ["GET", "/api/crm/lost-reasons"],
  ["POST", "/api/crm/lost-reasons"],
  ["POST", "/api/crm/lost-reasons/reorder"],
  ["PATCH", "/api/crm/lost-reasons/:id"],
  ["DELETE", "/api/crm/lost-reasons/:id"],
  ["GET", "/api/crm/tasks"],
  ["GET", "/api/crm/tasks/today"],
  ["POST", "/api/crm/tasks"],
  ["PATCH", "/api/crm/tasks/:id"],
  ["POST", "/api/crm/tasks/:id/complete"],
  ["POST", "/api/crm/tasks/:id/reopen"],
  ["POST", "/api/crm/tasks/:id/snooze"],
  ["DELETE", "/api/crm/tasks/:id"],
  // leaduri
  ["GET", "/api/crm/leads/pipeline"],
  ["GET", "/api/crm/leads/segments"],
  ["GET", "/api/crm/leads/export.csv", { file: true }],
  ["POST", "/api/crm/leads/bulk"],
  ["GET", "/api/crm/leads"],
  ["POST", "/api/crm/leads"],
  ["GET", "/api/crm/leads/:id"],
  ["GET", "/api/crm/leads/:id/detail"],
  ["PATCH", "/api/crm/leads/:id"],
  ["PATCH", "/api/crm/leads/:id/stage"],
  ["PATCH", "/api/crm/leads/:id/pipeline"],
  ["GET", "/api/crm/leads/:id/interactions"],
  ["POST", "/api/crm/leads/:id/interactions"],
  ["GET", "/api/crm/leads/:id/person-history"],
  // produse și stoc
  ["GET", "/api/crm/products"],
  ["POST", "/api/crm/products"],
  ["PATCH", "/api/crm/products/:id"],
  ["POST", "/api/crm/products/:id/archive"],
  ["POST", "/api/crm/products/:id/restore"],
  ["POST", "/api/crm/products/:id/stock/enable"],
  ["POST", "/api/crm/products/:id/stock/adjust"],
  ["POST", "/api/crm/products/:id/stock/threshold"],
  ["POST", "/api/crm/products/:id/stock/disable"],
  // import
  ["POST", "/api/crm/import/preview"],
  ["POST", "/api/crm/import/run"],
  ["GET", "/api/crm/import/mappings"],
  ["POST", "/api/crm/import/mappings"],
  ["DELETE", "/api/crm/import/mappings/:id"],
  ["GET", "/api/crm/import/jobs"],
  ["GET", "/api/crm/import/fields"],
  // acte, profilul firmei
  ["GET", "/api/crm/documents"],
  ["POST", "/api/crm/documents"],
  ["GET", "/api/crm/company-profile"],
  ["PUT", "/api/crm/company-profile"],
  // automatizări, repartizare, distribuție, ținte KPI, comunicare
  ["GET", "/api/crm/automations"],
  ["POST", "/api/crm/automations"],
  ["PATCH", "/api/crm/automations/:id"],
  ["DELETE", "/api/crm/automations/:id"],
  ["GET", "/api/crm/automations/runs"],
  ["POST", "/api/crm/automations/preview"],
  ["GET", "/api/crm/assignment/rules"],
  ["POST", "/api/crm/assignment/rules"],
  ["POST", "/api/crm/assignment/rules/reorder"],
  ["PATCH", "/api/crm/assignment/rules/:id"],
  ["DELETE", "/api/crm/assignment/rules/:id"],
  ["GET", "/api/crm/assignment/members"],
  ["PATCH", "/api/crm/assignment/members/:userId"],
  ["POST", "/api/crm/assignment/preview"],
  ["POST", "/api/crm/assignment/apply"],
  ["GET", "/api/crm/assignment/log"],
  ["POST", "/api/crm/distribution/preview"],
  ["POST", "/api/crm/distribution/run"],
  ["GET", "/api/crm/distribution/pool"],
  ["GET", "/api/crm/distribution/recall"],
  ["PUT", "/api/crm/distribution/recall"],
  ["GET", "/api/crm/kpi-targets"],
  ["PUT", "/api/crm/kpi-targets"],
  ["DELETE", "/api/crm/kpi-targets/:id"],
  ["POST", "/api/crm/comms/email"],
  ["POST", "/api/crm/comms/log"],
  ["GET", "/api/crm/comms/feed"],
].map(([method, p, flags = {}]) => ({ method, path: p, ...flags }));

export const hasParam = (e) => /:[a-zA-Z]+/.test(e.path);
export const withParam = (e, v) => e.path.replace(/:[a-zA-Z]+/g, v);
export const hasBody = (e) => ["POST", "PUT", "PATCH"].includes(e.method);
export const label = (e) => `${e.method} ${e.path}`;
