/**
 * AI-A02 — Rule-based churn risk scorer
 *
 * Computes a 0-100 risk score for each student based on:
 * - Attendance pattern (absences in last 14 days)
 * - Payment history (overdue invoices / high debt)
 * - Lesson scheduling (no upcoming lessons)
 *
 * No external LLM needed for scoring — this is entirely rule-based.
 * The suggested action text is generated by the AI client (stub-safe).
 */
import { and, eq, gte, lt, lte, isNull, sql } from "drizzle-orm";
import { db } from "../../db/client";
import {
  students,
  studentLessons,
  lessons,
  invoices,
  studentChurnScores,
} from "../../db/schema";

export interface ChurnRiskResult {
  studentId: string;
  studentName: string;
  score: number;
  factors: string[];
  trend: "rising" | "stable" | "falling";
}

/**
 * Compute churn risk score for a single student.
 * Returns null if the student doesn't exist in this tenant.
 */
export async function scoreChurnRisk(
  studentId: string,
  tenantId: string
): Promise<ChurnRiskResult | null> {
  // Verify student belongs to tenant
  const [student] = await db
    .select({ id: students.id, fullName: students.fullName })
    .from(students)
    .where(and(eq(students.id, studentId), eq(students.tenantId, tenantId)))
    .limit(1);

  if (!student) return null;

  let score = 0;
  const factors: string[] = [];

  const now = new Date();
  const fourteenDaysAgo = new Date(now.getTime() - 14 * 24 * 60 * 60 * 1000);
  const thirtyDaysAgo = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
  const fourteenDaysFromNow = new Date(now.getTime() + 14 * 24 * 60 * 60 * 1000);

  // ─── Factor 1: Absences in last 14 days (+30 if ≥ 3 absences) ───────────────
  const absences = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(studentLessons)
    .innerJoin(lessons, eq(studentLessons.lessonId, lessons.id))
    .where(
      and(
        eq(studentLessons.studentId, studentId),
        eq(studentLessons.attendanceStatus, "absent"),
        gte(lessons.scheduledAt, fourteenDaysAgo),
        lte(lessons.scheduledAt, now)
      )
    );

  const absenceCount = absences[0]?.count ?? 0;
  if (absenceCount >= 3) {
    score += 30;
    factors.push(`${absenceCount} absențe în ultimele 14 zile`);
  } else if (absenceCount >= 2) {
    score += 15;
    factors.push(`${absenceCount} absențe în ultimele 14 zile`);
  }

  // ─── Factor 2: Overdue invoices / high debt (+25) ────────────────────────────
  // Check for issued invoices older than 30 days that aren't paid
  const overdueInvoices = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(invoices)
    .where(
      and(
        eq(invoices.studentId, studentId),
        eq(invoices.status, "issued"),
        lt(invoices.createdAt, thirtyDaysAgo)
      )
    );

  const overdueCount = overdueInvoices[0]?.count ?? 0;
  if (overdueCount > 0) {
    score += 25;
    factors.push(`${overdueCount} factor${overdueCount > 1 ? "i" : "ă"} de plată restant${overdueCount > 1 ? "i" : "ă"} > 30 zile`);
  }

  // Also check debtCents on student
  const [studentDebt] = await db
    .select({ debtCents: students.debtCents })
    .from(students)
    .where(eq(students.id, studentId))
    .limit(1);

  if ((studentDebt?.debtCents ?? 0) > 50_000) { // > 500 RON
    if (overdueCount === 0) { // avoid double-counting
      score += 20;
      factors.push(`Sold negativ: ${((studentDebt?.debtCents ?? 0) / 100).toFixed(0)} RON`);
    }
  }

  // ─── Factor 3: No lesson scheduled in next 14 days (+20) ────────────────────
  const upcomingLessons = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(studentLessons)
    .innerJoin(lessons, eq(studentLessons.lessonId, lessons.id))
    .where(
      and(
        eq(studentLessons.studentId, studentId),
        gte(lessons.scheduledAt, now),
        lte(lessons.scheduledAt, fourteenDaysFromNow),
        eq(lessons.status, "scheduled")
      )
    );

  if ((upcomingLessons[0]?.count ?? 0) === 0) {
    score += 20;
    factors.push("Nicio lecție programată în 14 zile");
  }

  // ─── Factor 4: Check previous month's absence trend (+10) ───────────────────
  const prevMonthStart = new Date(now.getTime() - 60 * 24 * 60 * 60 * 1000);
  const prevMonthEnd = fourteenDaysAgo;

  const prevAbsences = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(studentLessons)
    .innerJoin(lessons, eq(studentLessons.lessonId, lessons.id))
    .where(
      and(
        eq(studentLessons.studentId, studentId),
        eq(studentLessons.attendanceStatus, "absent"),
        gte(lessons.scheduledAt, prevMonthStart),
        lte(lessons.scheduledAt, prevMonthEnd)
      )
    );

  const prevAbsenceCount = prevAbsences[0]?.count ?? 0;

  let trend: "rising" | "stable" | "falling" = "stable";
  if (absenceCount > prevAbsenceCount + 1) {
    trend = "rising";
    if (absenceCount > prevAbsenceCount) {
      score += 10;
      factors.push("Tendință crescătoare de absențe");
    }
  } else if (absenceCount < prevAbsenceCount) {
    trend = "falling";
  }

  // Cap score at 100
  score = Math.min(score, 100);

  return {
    studentId: student.id,
    studentName: student.fullName,
    score,
    factors: factors.slice(0, 3), // top 3 factors
    trend,
  };
}

/**
 * Compute churn risk for all active students in a tenant.
 * Returns only students with score > 0 (those worth flagging).
 */
export async function scoreAllStudents(
  tenantId: string
): Promise<ChurnRiskResult[]> {
  const allStudents = await db
    .select({ id: students.id })
    .from(students)
    .where(
      and(eq(students.tenantId, tenantId), eq(students.status, "active"))
    )
    .limit(200); // safety cap

  const results: ChurnRiskResult[] = [];

  for (const s of allStudents) {
    const result = await scoreChurnRisk(s.id, tenantId);
    if (result && result.score > 0) {
      results.push(result);
    }
  }

  return results.sort((a, b) => b.score - a.score);
}
